#make file for TCP client-server
all:
	gcc -o chat_server chat_server.c
	gcc -o chat_client chat_client.c

server:
	gcc -o chat_server chat_server.c
	
client:
	gcc -o chat_client chat_client.c
clean:
	rm chat_client chat_server



